language: node_js
node_js: '11'
before_script:
- npm run test
script: npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_373965b62ca2_key -iv $encrypted_373965b62ca2_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
